# Generated by Django 4.1.5 on 2023-01-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shop',
            new_name='shopDB',
        ),
    ]
